### ISSUE TITLE
Failure: plugin prost: proto: cannot parse invalid wire-format data

### ISSUE THREAD

**Issue by hexfusion** [neoeinstein/protoc-gen-prost#33]
Plugin is failing with rust 1.65 stable, I am going to try and take a deeper look but any help would be great.
```
Failure: plugin prost: proto: cannot parse invalid wire-format data; context canceled; signal: killed; signal: killed; signal: killed; context canceled; context canceled; context canceled; signal: killed; signal: killed; signal: killed; context canceled
ERROR: buf generate proto stubs failed
```

**Comment by hexfusion** [comment]
The error actually comes from protoc decode directly[1] which is unfortunate.

What is interesting is that the latest version of the plugins from registry actually do work using as remote.

```
version: v1
plugins:
  - remote: buf.build/prost/plugins/prost:v0.2.0-2
```

https://buf.build/prost/plugins

[1] https://github.com/protocolbuffers/protobuf-go/blob/master/proto/decode.go#L294

**Comment by neoeinstein** [comment]
Generally this means something that there was something invalid or that caused a panic. I wasn't able to reproduce the error rebuilding locally and using my public or internal protobuf test sets using the following versions:

* `rustc`: 1.65
* `protoc`: 3.21.9
* `buf`: 1.9.0

What versions are you using, respectively?

Often what this means is that there was some sort of panic that occurred, as it probably produced plain text rather than the protobuf report of an error that was expected. In general, the only reasons that a panic should occur is because of an error in reading from `stdin` or writing to `stdout`.

If we're all working on effectively the same versions, then perhaps you may be able to exclude things from your input set until you get to a non-working minimal example, and then we can work that into a test to make sure we're properly handling that case.

**Comment by hexfusion** [comment]
Thanks for quick reply, yeah working on a minimal working example now.
```
rustc: 1.65
protoc: 3.21.3
buf: 1.9.0
```

**Comment by hexfusion** [comment]
Here is my minimal example using helloworld.

```
cd src/proto/
buf generate

Failure: plugin prost: proto: cannot parse invalid wire-format data
```

[1] https://github.com/hexfusion/prost-plugin-debug/tree/master/prost-plugin-debug/src/proto

**Comment by hexfusion** [comment]
another thing to note is this was working in a compiled version with an older rust. When I removed the binary and did cargo install I saw the failure.

**Comment by neoeinstein** [comment]
I think I found it.

https://sourcegraph.com/crates/prost-build/-/compare/v0.11.0...v0.11.2#diff-bbff921c19d129ecd0dda049b127e8d1R113

This `println!` would be printing to `stdout`, which would interfere with our communications with `protoc`, but would otherwise be invisible to anyone using `prost-build` in a build script. This `println!` was introduced in `prost-build@0.11.2`. I'll get a PR prepared over there to get that fixed.

To get back to working, I'd recommend running `cargo install protoc-gen-prost --locked --version 0.2.0`. That will use the locked version of all dependencies as of publishing, which was `0.11.0`.

**Comment by neoeinstein** [comment]
It appears that this was also reported there previously in tokio-rs/prost#745. With a release there, I'll provide a new minimum version that ensures consumers don't accidentally bind to that version of `prost-build`.

**Comment by hexfusion** [comment]
Circling back around it looks like https://github.com/tokio-rs/prost/releases/tag/v0.11.4 has been cut :)
