### ISSUE TITLE
[FEATURE-REQUEST] Way to disable transport feature for tonic_build

### ISSUE THREAD

**Issue by stan-irl** [neoeinstein/protoc-gen-prost#42]
Hi!

I want to compile my generated rust protos to `wasm-unknown-unknown` but the generate `::connect()` method doesn't compile to wasm. The connect method can be omitted by disabling the `transport` feature of `tonic_build` as documented [here](https://docs.rs/tonic-build/latest/tonic_build/) and I've tested that this works as expected by using `tonic_build` directly.

@neoeinstein do you have any idea how I can disable this? Is it possible in the current implementation of `protoc-gen-tonic`?

**Comment by neoeinstein** [comment]
At the current moment, no, unfortunately, because I cannot conditionally enable a dependency's features at runtime. (Though I _could_ duplicate a `protoc-gen-tonic-no-transport`, I'd like to avoid the overhead of a completely distinct executable.) However, [this PR](https://github.com/hyperium/tonic/pull/1112) has been merged into `tonic-build`, which should allow us to expose an argument to include the batteries-included transport or not at runtime (and without needing a completely distinct executable).

If you wanted to give this a test, you could pull down the repository, add a `[patch]` block to the Cargo.toml pointing at `tonic`'s default branch, and see if what would be necessary to get it to compile and expose the option.

Once a new version of Tonic releases with this new functionality, I'd be happy to merge in a PR for this, or update it myself when I have the next opportunity.

**Comment by stan-irl** [comment]
ok sure. i will have a go
