### ISSUE TITLE
Failure with tonic when a proto file has only service definitions

### ISSUE THREAD

**Issue by Rockin2** [neoeinstein/protoc-gen-prost#61]
If there is a proto file that has only service definitions like that ,

````proto
syntax = "proto3";

package b.a;

import "common.proto";

service BService {
  rpc Create(b.common.Request)
    returns (b.common.Response);

  rpc Get(b.common.Request)
    returns (b.common.Response);
}
````

the compilation will fail with this message .

`b.a.rs: Tried to insert into file that doesn't exist.`

A workaround is to add a type like that in the file.

````proto
enum TestEnum {
  ZERO = 0;
  ONE = 1;
  TWO = 2;
}
````

What happen I think is Prost doesn’t generate b.rs because it is empty so tonic cannot add its b.tonic.rs include to it.
Maybe it is related to issue [#59](https://github.com/neoeinstein/protoc-gen-prost/issues/59).

**Comment by yibo-long** [comment]
We got this issue too, and similar found the walkaround by defining a test message. It will be great if we don't have to do that.

I also tried adding `--include-imports` in the buf generate command but still got the same error.

**Comment by Tuetuopay** [comment]
Hi, get my upvote.

The plugins are now unusable with buf when such a situation arises, because you cannot use the "single protoc invocation" trick mentioned in the readme. And using the `no_imports` flag of the tonic plugin is a nogo especially when using prost-crate.

So please make the plugins output insertion points in prost-crate's include file to have actual imports of the tonic generated files.

**Comment by DavidDomkar** [comment]
Hi. I have the some problem. Any idea when this could be resolved?

**Comment by fenollp** [comment]
Hey @neoeinstein do you have some guidelines on this? Maybe a WIP branch somewhere?

**Comment by fenollp** [comment]
FYI this fixes it https://github.com/neoeinstein/protoc-gen-prost/pull/58

**Comment by Rockin2** [comment]
Seems to work. :)
