### ISSUE TITLE
Suggestion: support the `prost_build::Config::include_file` option

### ISSUE THREAD

**Issue by bradzacher** [neoeinstein/protoc-gen-prost#93]
I see that it's supported within [`protoc-gen-prost-crate`](https://github.com/neoeinstein/protoc-gen-prost/blob/main/protoc-gen-prost-crate/README.md) - though I don't specifically want to generate a crate for the types and instead just want to generate a set of files for me to consume within my existing crate.

I'd love to have it as part of the base codegen package.

**Comment by bradzacher** [comment]
For my usecase I'm consuming this via bazel (https://rules-proto-grpc.com/en/4.5.0/lang/rust.html).
I just figured out that the bazel rule already uses the `-crate` binary (as well as the base binary). So I can enable this behaviour with the following option in the rule:
```
    options = {
        "@rules_proto_grpc//rust:rust_crate_plugin": [
            "include_file=_include.rs",
        ],
    },
```

So I'll close this as my usecase is satisfied.

**Comment by neoeinstein** [comment]
I'm unlikely to reopen this at this time, as the `include_file` option causes `prost-build` to directly write the file to an output path in a manner that is incompatible with a `protoc` plugin. Protoc plugins are not supposed to directly write to the filesystem, and are instead supposed to mediate all file creation through `protoc` itself.

You might ask to port the `-crate` include file implementation into `-prost`, but there we would encounter issues. By default, `buf` invokes the `protoc-gen-prost` plugin once per directory _in parallel_. (A strategy must be explicitly specified to disable this behavior.) This results in issues due to conflicting concurrent attempts to write to the include file. This behavior would likely lead to more bug reports due to incorrect usage.

Generating an include file explicitly requires all of the proto files at the same time, which is why it's recommended as a distinct step in a `buf` workflow utilizing the `all` strategy. 

Separating the crates by default allows for significantly faster execution, especially on large protobuf repositories, and avoids "You aren't holding it right"-style bugs.

The functionality in `protoc-gen-prost-crate` is more robust, and more directly leads to correct usage, which is why I've made it the supported and documented mechanism.

**Comment by stefanvanburen** [comment]
> You might ask to port the `-crate` include file implementation into `-prost`, but there we would encounter issues.

Yeah, this is what I'd be asking for. Looking to do some slightly unconventional things with the individual plugins that involves running them in isolation and generating separate crates for each, so I'm less concerned with concurrent writes to the includes files. I suppose I could run the plugins individually followed by the `-crate` plugin just to generate the includes files, but was hoping to avoid that.

I completely understand, though, that my individual use-case conflicts with the maintainability of this project - just would rather be able to leverage the logic of the generator for creating the includes file than rewriting it myself 😄. Thanks for the great plugins!
